/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marswin89_marsdaemon_nativ_NativeDaemonAPI21 */

#ifndef _Included_com_marswin89_marsdaemon_nativ_NativeDaemonAPI21
#define _Included_com_marswin89_marsdaemon_nativ_NativeDaemonAPI21
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marswin89_marsdaemon_nativ_NativeDaemonAPI21
 * Method:    doDaemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xmpp_client_FormLogin_lockself
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_com_xmpp_client_FormLogin_watch
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);
//JNIEXPORT void JNICALL Java_com_sdk_one_MainActivity_startDaemonApp(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
